set -g fish_color_autosuggestion 777777
set -g fish_color_command 80FF80
set -g fish_color_comment 80BE80
set -g fish_color_end FF7B7B
set -g fish_color_error FF0000
set -g fish_color_param CFFFCF
set -g fish_color_quote CFFFA0
set -g fish_color_redirection 7BFF7B
set -g fish_color_operator 40FFDF
