set -U tide_aws_bg_color 303030
set -U tide_aws_color FFA000
set -U tide_character_bg_color normal
set -U tide_character_color 5FD700
set -U tide_character_color_failure FF0000
set -U tide_character_icon \u276f
set -U tide_character_vi_icon_default \u276e
set -U tide_character_vi_icon_replace \u25b6
set -U tide_character_vi_icon_visual V
set -U tide_chruby_bg_color 303030
set -U tide_chruby_color B31209
set -U tide_chruby_icon \ue23e
set -U tide_cmd_duration_bg_color 303030
set -U tide_cmd_duration_color 87875F
set -U tide_cmd_duration_decimals 0
set -U tide_cmd_duration_icon \x1d
set -U tide_cmd_duration_threshold 3000
set -U tide_context_always_display false
set -U tide_context_bg_color 303030
set -U tide_context_color_default D7AF87
set -U tide_context_color_root D7AF00
set -U tide_context_color_ssh D7AF87
set -U tide_git_bg_color 303030
set -U tide_git_bg_color_unstable 303030
set -U tide_git_bg_color_urgent 303030
set -U tide_git_color_branch 5FD700
set -U tide_git_color_conflicted FF0000
set -U tide_git_color_dirty D7AF00
set -U tide_git_color_operation FF0000
set -U tide_git_color_staged D7AF00
set -U tide_git_color_stash 5FD700
set -U tide_git_color_untracked 00AFFF
set -U tide_git_color_upstream 5FD700
set -U tide_git_icon \ue0a0
set -U tide_go_bg_color 303030
set -U tide_go_color 00ACD7
set -U tide_go_icon \ue627
set -U tide_jobs_bg_color 303030
set -U tide_jobs_color 5FAF00
set -U tide_jobs_icon \uf013
set -U tide_kubectl_bg_color 303030
set -U tide_kubectl_color 326CE5
set -U tide_kubectl_icon \u2388
set -U tide_left_prompt_frame_enabled false
set -U tide_left_prompt_items pwd\x1egit\x1enewline\x1echaracter
set -U tide_left_prompt_prefix \ue0b6
set -U tide_left_prompt_separator_diff_color \ue0b0
set -U tide_left_prompt_separator_same_color \ue0b5
set -U tide_left_prompt_suffix \ue0b4
set -U tide_node_bg_color 303030
set -U tide_node_color 44883E
set -U tide_node_icon \u2b22
set -U tide_os_bg_color 303030
set -U tide_os_color EEEEEE
set -U tide_os_icon \uf312
set -U tide_php_bg_color 303030
set -U tide_php_color 617CBE
set -U tide_php_icon \ue608
set -U tide_prompt_add_newline_before true
set -U tide_prompt_color_frame_and_connection 6C6C6C
set -U tide_prompt_color_separator_same_color 949494
set -U tide_prompt_icon_connection \x20
set -U tide_prompt_min_cols 26
set -U tide_prompt_pad_items true
set -U tide_pwd_bg_color 303030
set -U tide_pwd_color_anchors a0ffa0
set -U tide_pwd_color_dirs cfffa0
set -U tide_pwd_color_truncated_dirs cfffa0
set -U tide_pwd_icon \x1d
set -U tide_pwd_icon_home \x1d
set -U tide_pwd_icon_unwritable \uf023
set -U tide_pwd_markers \x2ebzr\x1e\x2ecitc\x1e\x2egit\x1e\x2ehg\x1e\x2enode\x2dversion\x1e\x2epython\x2dversion\x1e\x2eruby\x2dversion\x1e\x2eshorten_folder_marker\x1e\x2esvn\x1e\x2eterraform\x1eCargo\x2etoml\x1ecomposer\x2ejson\x1eCVS\x1ego\x2emod\x1epackage\x2ejson
set -U tide_pwd_truncate_margin 40
set -U tide_right_prompt_frame_enabled false
set -U tide_right_prompt_items status\x1ecmd_duration\x1econtext\x1ejobs\x1enode\x1evirtual_env\x1evi_mode\x1eaws
set -U tide_right_prompt_prefix \x2d\x20\x20\ue0b6
set -U tide_right_prompt_separator_diff_color \ue0b7
set -U tide_right_prompt_separator_same_color \ue0b7
set -U tide_right_prompt_suffix \ue0b4
set -U tide_rustc_bg_color 303030
set -U tide_rustc_color F74C00
set -U tide_rustc_icon \ue7a8
set -U tide_shlvl_bg_color 303030
set -U tide_shlvl_color d78700
set -U tide_shlvl_icon \uf120
set -U tide_shlvl_threshold 1
set -U tide_status_bg_color 303030
set -U tide_status_bg_color_failure 303030
set -U tide_status_color 5FAF00
set -U tide_status_color_failure D70000
set -U tide_status_icon \u2714
set -U tide_status_icon_failure \u2718
set -U tide_time_bg_color 303030
set -U tide_time_color 5F8787
set -U tide_time_format
set -U tide_vi_mode_bg_color_default 303030
set -U tide_vi_mode_bg_color_replace 303030
set -U tide_vi_mode_bg_color_visual 303030
set -U tide_vi_mode_color_default 87af00
set -U tide_vi_mode_color_replace d78700
set -U tide_vi_mode_color_visual 5f87d7
set -U tide_vi_mode_icon_default DEFAULT
set -U tide_vi_mode_icon_replace REPLACE
set -U tide_vi_mode_icon_visual VISUAL
set -U tide_virtual_env_bg_color 303030
set -U tide_virtual_env_color 00AFAF
set -U tide_virtual_env_icon \ue73c
